use_frameworks!

target 'YunBaSDK_Example' do
  pod 'YunBaSDK', :path => '../'

  target 'YunBaSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
